# Generated by Django 4.2.4 on 2023-08-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=20)),
                ('delivered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_order', to='users.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods_in_order', to='foods.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_number', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(related_name='oder_foods', through='orders.OrderFood', to='foods.food'),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_tg_users', to='users.telegramuser'),
        ),
    ]
