# Generated by Django 4.2.4 on 2023-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Yetkazib berish'), ('take_away', 'Olib ketish')], default='take_away', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='takeaway_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('preparing', 'Tayyorlanmoqda'), ('prepared', 'Tayyor'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Topshirildi'), ('canceled', 'Bekor Qilindi')], default='new', max_length=20),
        ),
    ]
