# Generated by Django 4.2.4 on 2023-08-31 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_image'),
        ('orders', '0002_order_delivery_price_order_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods_in_order', to='foods.food'),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_number', to='orders.order'),
        ),
    ]
