# Generated by Django 4.2.4 on 2023-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderfood_food_alter_orderfood_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=20),
        ),
    ]
