# Generated by Django 4.2.4 on 2023-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=30),
        ),
    ]
