# Generated by Django 4.2.4 on 2023-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('sent', 'Yuborilgan'), ('not_sent', 'Yuborilmagan')], max_length=30),
        ),
    ]
